import type { Metadata } from 'next';
import { Libre_Baskerville } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Alejandra Noemi Queiruga',
  description: 'Generated by create next app',
};

// Inicializar la fuente
const libreBaskerville = Libre_Baskerville({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '700'], // elegí los pesos que necesites
  style: ['normal', 'italic'], // <-- agrega esto
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${libreBaskerville.className}`}>{children}</body>
    </html>
  );
}
